server:
  port: 9601

spring:
  redis:
    host: ${env.redis.host}
    password: ${env.redis.password}
    port: ${env.redis.port}
    database: ${env.redis.database}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms

gcdp:
  cloudt:
    gateway:
      baseUrl: ${env.cloudt.gateway.baseUrl}

gect:
  product:
    appkey: ${env.cloudt.gateway.appKey}
    appsecret: ${env.cloudt.gateway.appSecret}
  service:
    ignoreActionHandlerNotFound: ${env.gect.service.ignoreActionHandlerNotFound}
    onlySendOpenEvent: ${env.gect.service.onlySendOpenEvent}
  cloudt:
    hostUrl: ${env.gect.cloudt.hostUrl}
  streamsService:
    hostUrl: ${env.gect.streamsService.hostUrl}


meta:
  registry:
    hostUrl: ${env.gect.registry.hostUrl}

coral:
  common:
    data:
      rest:
        hostUrl: ${env.gect.cds.hostUrl}
  meta:
    registry:
      discovery:
        deployments:
          #模块.产品.租户
          - xxx.xxx.xxx
        kinds:
          - Service
